apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: qq2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

#command
#kubectl create namespace qq2
#kubectl apply -f nginx.yaml
