apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-deployment
  namespace: qq2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab
  template:
    metadata:
      labels:
        app: lab
    spec:
      containers:
      - name: lab-container
        image: nginx
        ports:
        - containerPort: 80

#command
#kubectl create namespace qq2
#kubectl apply -f lab-deployment.yaml
#kubectl scale deployment lab-deployment --replica=4 -n qq2
